[tox]
envlist = py312

[testenv]
constrain_package_deps = true
deps =
    -c constraints-modern.txt
    ecreall_dace @ git+https://github.com/michaellaunay/dace.git
    zope.testrunner
extras = test
commands =
    python -m zope.testrunner --test-path=. -s pontus {posargs}
